# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json

apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: jacob-dev
  annotations:
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: frontend
      variables:
        USE_SWAGGER: "true"
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 1234
      environmentConfig:
        - environment: dev
          horizontalScaling:
            maxReplicas: 1
            minReplicas: 0
            triggers:
              - name: cron
                cron:
                  timezone: Europe/Oslo
                  start: 0 7 * * 1-5 # 07:00 Monday - Friday
                  end: 0 17 * * 1-5 # 17:00 Monday - Friday
                  desiredReplicas: 1
          resources:
            requests:
              cpu: "10m"
              memory: "5M"
            limits:
              cpu: "20m"
              memory: "10Mi"
      runAsUser: 1337
      authentication:
        oauth2:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          setAuthorizationHeader: true
          credentials: azureWorkloadIdentity
          sessionStoreType: systemManaged # Defaults to cookie, can be systemManaged, redis or cookie
          cookieStore:
            minimal: false
          cookie:
            name: _oauth2_proxy
            expire: 168h0m0s
            refresh: 60m0s
            sameSite: lax
  jobs:
      - name: cron-job
        image: alpine:3
        schedulerPort: 8080
        command: ["/bin/sh"]
        args: ["-c", "echo 'Hello from cron job!'; sleep 90"]
        runAsUser: 1000
        cron:
          timeZone: "Europe/Oslo"
          #timeZone: "America/New_York"
          schedule: 
            #- "* * * * 1"
            - "*/1 * * * *"
            #- "@daily"
          concurrency: "Replace" # Allow, Forbid, Replace. Naming based on k8s concurrency policy: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy